### PR TITLE
[New] Created ShareWidget component

### LINKED ISSUE #19: Create ShareWidget Component
Create the ShareWidget component:
image

WET reference: https://wet-boew.github.io/v4.0-ci/demos/share/share-en.html

### PR DESCRIPTION
**Pull request by P4ul1029**
⭐ **New Features:**
Created the ShareWidget component. I had to merge the following branches for the component to function:
- regeneratorRuntime-error-fix
- css-default-not-a-function-bug-fix
- icons-documentation

ℹ️ **Related Issues:**
Closes #19 

📷 **Screenshots:** _(if applicable)_
image

### CODE REVIEW

**Review by Rizvida1 — CHANGES_REQUESTED** [review]
Could you resolve the merge conflicts?

**Comment by P4ul1029** [comment]
> Could you resolve the merge conflicts?

Done!

**Comment by Rizvida1** [comment]
> In the screenshot above, the `Modal.Header` background defaulted to black: image
> 
> Should I leave it as is, or should I use styles to change it to blue like in the original ShareWidget component? image

We should make it blue I think

**Comment by P4ul1029** [comment]
> > In the screenshot above, the `Modal.Header` background defaulted to black: image
> > Should I leave it as is, or should I use styles to change it to blue like in the original ShareWidget component? image
> 
> We should make it blue I think

Done!

**Review by Rizvida1 — APPROVED** [review]

**Pull request merged**
